### ISSUE TITLE
[Chore] [iOS] Configure CI for the project

### ISSUE THREAD

**Issue by nmint8m** [nimblehq/ic-kmm-kayla-bruce#3]
## Why

To improve production quality, continuous integration (CI) takes an important part in the development process.

## Acceptance criteria

Set up a CI pipeline that satisfies the development standard.

- Build application in CI
- Run unit tests
- Support linting for checking code convention

**Comment by markgravity** [comment]
We may need to separate it into iOS & Android task 🙏

**Comment by markgravity** [comment]
Just make sure we have set up DI and BuildKonfig or we can create other tasks for these🙏
